# Generated by Django 3.1.4 on 2021-01-18 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bounties', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bounty',
            old_name='name',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='total',
        ),
        migrations.AddField(
            model_name='hunter',
            name='balance',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bounties.organization')),
            ],
        ),
    ]
