# Generated by Django 3.1.4 on 2021-01-18 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bounties', '0002_auto_20210117_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='hunter',
            name='bounties',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='hunter',
            name='points',
            field=models.FloatField(default=0),
        ),
    ]
