# Generated by Django 3.1.4 on 2021-01-18 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bounties', '0003_auto_20210117_2148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('description', models.TextField(max_length=200, null=True)),
            ],
        ),
    ]
